version: '3.8'

services:
  web-api:
    build: 
      context: .
      dockerfile: Web2/Dockerfile
    container_name: modelsecurityda
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=nombre-contenedor-bd,1433;Database=ModelSecurityDa;User Id=sa;Password=StrongPwd!123;Encrypt=True;TrustServerCertificate=True;Connection Timeout=60;
    ports:
      - "5112:8080"
    networks:
      - nombre-de-tu-red-existente
    restart: unless-stopped

networks:
  nombre-de-tu-red-existente:
    external: true